apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-student
  namespace: levelup-learning
  labels:
    app: frontend-student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-student
  template:
    metadata:
      labels:
        app: frontend-student
    spec:
      containers:
      - name: frontend-student
        image: surajahasarinda/levelup-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-student
  namespace: levelup-learning
  labels:
    app: frontend-student
spec:
  selector:
    app: frontend-student
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP