name: Build and Deploy Frontend Student

on:
  push:
    branches: [ vhbranch3 ]     # Build + deploy on this branch
  pull_request:
    branches: [ main ]           # Only build/test on PR to main

env:
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: asia-south1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: levelup-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # 3️ Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4️ Build application
    - name: Build application
      run: npm run build

    # 5️ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6️ Build Docker image (two tags: commit SHA + latest)
    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA \
                     -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

    # 7️ Push Docker images
    - name: Push Docker image
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    # 8️ Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 9️ Setup Google Cloud CLI
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 10 Install GKE Auth Plugin (required for Autopilot)
    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin -q

    # 1️1️ Deploy to GKE (only on vhbranch3 push)
    - name: Deploy to GKE
      if: github.ref == 'refs/heads/vhbranch3'
      run: |
        # Get cluster credentials
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

        # Update deployment image
        kubectl set image deployment/frontend-student \
          frontend-student=$DOCKERHUB_USERNAME/$IMAGE_NAME:$GITHUB_SHA \
          --namespace=levelup-learning

        # Wait for rollout to complete
        kubectl rollout status deployment/frontend-student --namespace=levelup-learning
