name: Build and Deploy Frontend Student

on:
  push:
    branches: [ deployment ]

  pull_request:
    branches: [ main ]

env:
  GKE_CLUSTER: levelup-cluster
  GKE_ZONE: asia-south1-a
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: levelup-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA \
                     -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Push Docker image
      run: |
        docker push $DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA
        docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE (if main branch)
      if: github.ref == 'refs/heads/deployment'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        kubectl set image deployment/frontend-student \
          frontend-student=$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA \
          --namespace=levelup-learning
        kubectl rollout status deployment/frontend-student --namespace=levelup-learning