name: Build and Deploy Frontend Student

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.js'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'

env:
  GKE_CLUSTER: levelup-cluster
  GKE_ZONE: us-central1-a
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: levelup-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA \
                     -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .

    - name: Push Docker image
      run: |
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Deploy to GKE (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
        kubectl set image deployment/frontend-student \
          frontend-student=gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA \
          --namespace=levelup-learning
        kubectl rollout status deployment/frontend-student --namespace=levelup-learning